server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:1234/jca_db
    username: jeff.adami
    password: Adami44
    driver-class-name: org.postgresql.Driver
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic: jca-teste-topic